apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter
spec:
  template:
    spec:
      containers:
      - name: jmeter
        image: patrocinio/jmeter:5.4
        imagePullPolicy: Always
#        command: ["/bin/sh", "-ec", "sleep 1000"]
        volumeMounts:
        - mountPath: "/opt/apache-jmeter-5.4/tests/ibmmq"
          name: test-pvc
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 4
      volumes:
      - name: test-pvc
        persistentVolumeClaim:
          claimName: jmeter-pvc
      restartPolicy: Never
