apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter
spec:
  template:
    spec:
      containers:
      - name: jmeter
        image: patrocinio/jmeter:5.4
        imagePullPolicy: Always
      restartPolicy: Never
