apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter
  labels:
    app: jmeter
spec:
  template:
    spec:
      containers:
      - name: jmeter
        image: patrocinio/jmeter:5.4
        imagePullPolicy: Always
        command: 
      restartPolicy: Never
